### ISSUE TITLE
[BUG] Blackboard interface for RegisterEntry + SetEntryValue needs rethinking

### ISSUE THREAD

**Issue by jankrassnigg** [ezEngine/ezEngine#1062]
RegisterEntry ONLY changes the value when the entry didn't exist yet.
SetEntryValue FAILS, if the entry didn't exist yet.

Thus a lot of code will either need to call both, or potentially fails to do the desired thing.

The separation has been done because of hashedstring vs temphashedstring interfaces. Maybe this needs to be thought over again.

**Comment by C-Core** [comment]
The separation was initially done so that you don't  accidentally set "unknown" values. Basically as a check that you have spelled the entry name correctly. But I can see that this is annoying and we can probably get rid of the whole register thing. But there should be a way to set the flags separately from the value so you don't have to pass the flags every time you want to change the value.

**Comment by jankrassnigg** [comment]
To prevent people from typing the wrong key names in the editor, we could use the DynamicStringEnum feature.

Agreed that setting the flags should be decoupled from setting the value.
