### ISSUE TITLE
[FEATURE] Allow storing game object/component handles in blackboard/variant.

### ISSUE THREAD

**Issue by x0r04rg** [ezEngine/ezEngine#1201]
Ability to store a handle to other game objects or components is necessary for AI and probably some gameplay systems. Currently, it can be worked around, but requires custom code and is inconvenient. 

It should contain type information to differentiate between game object and component handles. Also, since there is a new typed component handles feature now, it should probably differentiate between component types as well.

Also, visual script local variables are variants too, so fixing it would also allow storing handles in visual script (which is also really useful).

Not sure what's the best way to do it since `ezVariant` is part of the Foundation and doesn't know anything about game objects and components. One way I can think of is: add "subtype" to `ezVariant` similar to `ezTypedPointer` but composed of `ezGenericId` + `ezRTTI`, add overloads to `ezWorld::TryGetObject` and `ezWorld::TryGetComponent` that receive `ezVariant` (?) as an argument.

**Comment by C-Core** [comment]
You can already store ezGameObjectHandle and ezComponentHandle in a variant. It is implemented via the ezTypedObject path in the variant. Typed component handles don't make much sense in an ezVariant since you have to do runtime checks for variant code anyways.

The only problem is that all of that is not exposed on the Editor side, thus you won't see a GameObject or Component entry in the type dropdown menu. That needs to be improved at some point.

**Comment by x0r04rg** [comment]
Yes, you are correct, I missed that somehow.
