### ISSUE TITLE
[BUG] ezVisualScriptNodeRegistry crashes when function is exposed incorrectly

### ISSUE THREAD

**Issue by jankrassnigg** [ezEngine/ezEngine#1221]
I have a function that was originally declared with one argument, but then a second was added:

```cpp
void DoStuff(const ezVec3& pos, bool b);
```

The function declaration was forgotten to be fixed:

```cpp
EZ_SCRIPT_FUNCTION_PROPERTY(DoStuff, In, "Position"),
```

This now crashes at startup in `ezVisualScriptNodeRegistry::CreateFunctionCallNodeType` trying to call `pScriptableFunctionAttribute->GetArgumentName` for the second argument.

Somehow the code knows that the function really has two arguments, and tries to access this data.

1. Since this can happen to anyone easily, it would be nicer to have better feedback. Best case it's already a compilation error. Or it is an assert with a very clear description of what one did wrong.
2. How does this work with functions that have default arguments, and you may not want to expose the default argument, at all? Is that something that should work?

**Comment by C-Core** [comment]
It should not crash, agreed.
1. It can't be a compilation error since the EZ_SCRIPT_FUNCTION_PROPERTY does two things: It reflects the function with our regular function reflection (this is also where it knows how many arguments it has and what the types are) and it adds a ezScriptableFunctionAttribute which contains the names and whether it is an in or out parameter. Both don't know about each other.
2. All arguments are exposed, if you don't want that you need to create a second function with only the arguments that should be exposed and reflect that. Default values need to be added to reflection via ezFunctionArgumentAttributes(argIndex, new ezDefaultValueAttribute(bla)).
