### ISSUE TITLE
Visual Scripts: Vector types should expose more functionality

### ISSUE THREAD

**Issue by jankrassnigg** [ezEngine/ezEngine#1224]
If you get a "Vector3" type from a function, there is very little you can do with it. There is currently no way to access the x,y,z components. There are no "GetLength()" etc functions. Interestingly for "Quat" some functions exist (GetX, GetY, MakeSomething).

I don't understand why there are GetXYZW functions for Quat, but not for Vec3, since both are reflected. I assume it is because Quat also has two reflected functions, and maybe the Vec3 getters are not exposed if there is no reflected function, at all?

The only way to work with Vec3 that I found was to use a math expression, because there "sqrt" exists, so I could compute the length manually.

I think we need to expose a lot of functionality for:
* Vec2, Vec3, Vec4
* Quat
* Transform (?)
* Bounding Box / Sphere (?)

**Comment by C-Core** [comment]
Properties are only exposed for types that have reflected functions as well, otherwise you would end up with so many types and most of them would be not even usable in visual script. I have only reflected the functions that I needed so far, but if you need more just reflect them.
There is no need to compute the length manually in expressions, just use the "length" function as you would in hlsl. There is also "normalize", "dot", "cross" and "reflect" in expressions (see ezExpressionParser::RegisterBuiltinFunctions for the full list).
Vec2, Vec4, Bounding Box / Sphere are not supported as types in Visual Script.

**Comment by jankrassnigg** [comment]
Added a few functions in #1225. There were not that many useful functions for visual scripting as I had thought.
