### ISSUE TITLE
[BUG] Sometimes Asset Browser forgets where i am

### ISSUE THREAD

**Issue by PlasmaDev5** [ezEngine/ezEngine#1255]
There are multiple occasions where the asset browser has created folders and assets in the wrong directory. For example loading the engine navigating to a folder in the main thumbnail view and creating a level will create it at root. Iv had similar occasions with folders and its proven to be very frustrating when it happens

**Comment by jankrassnigg** [comment]
Can you record a video with steps to reproduce?

**Comment by PlasmaDev5** [comment]
https://github.com/ezEngine/ezEngine/assets/3044415/d516d95b-49bc-4eb2-9e87-cb9c8596158d

**Comment by jankrassnigg** [comment]
Figured out under which circumstances this happens. It's when you go to a folder on the right side, not the left, because the "new asset" code uses the "current" Qt item, but that is not the same as the "selected" item, and when you enter a folder on the right, the "current" item is not changed.

Fix should be easy, once I get the time to do it.

If anyone else wants to fix it, see ezQtAssetBrowserWidget::NewAsset().
