### ISSUE TITLE
[BUG] Changing SetWorldSimulationEnabled creates inconsistent behavior

### ISSUE THREAD

**Issue by RiederAlex** [ezEngine/ezEngine#1300]
Games need a way to pause/unpause the simulation - however doing this the most straighforward way via `pWorld->SetWorldSimulationEnabled(true/false)` inside a components update causes inconsistencies.

The main issue is that `pWorld->SetWorldSimulationEnabled(true/false)` instantly resumes simulating during `ezWorld::Update`, causing only parts of a frame being simulated.
This is double bad if unpausing, as this causes `GetWorld()->GetClock().GetTimeDiff().AsFloatInSeconds()` to be 0 for the rest of the frame while updating components which do not expect it (e.g. where `m_bOnlyUpdateWhenSimulating` = true), causing assertions/divides by 0/ect. 
See `void ezWorld::UpdateSynchronous` for an example where this happens.

**Proposed solutions**

1. `ezWorld::Get/Set WorldSimulationEnabled` are delayed
    A new boolean is introduced which remembers the desired state of the world simulation and flushes it into `m_Data.m_bSimulateWorld` at the beginning of the Update() loop
    With this solution I'm afraid of side effects I do not know about and certain decisions have to be made which might not be easily understandable as a user, like if GetWorldSimulationEnabled() return the current state of or the desired state.

2. Pause/Unpause is implemented in GameState and delayed
    Similar to proposed solution 1, but with a lot less side effects as its a new API - we implement a Pause/Unpause/IsPaused in GameState and flush it in `GameState::ProcessInput()`. 
This would give users a clear way to pause the simulation, but it would introduce a new API which accomplishes something that can also be done differently (via directly accessing the world), which is always a sub-optimal solution.

3. `ezWorld::Update()` saves the state of m_bSimulateWorld at the beginning of the call and runs the rest of the update loop with that state
      So calls like `ezWorld::UpdateSynchronous` or `ezWorld::UpdateAsynchronous` would no longer use `m_Data.m_bSimulateWorld`, but instead something like `bSimulateThisFrame`, which is a constant value set at the beginning of `ezWorld::Update()`

Personally I think solution 3 is the one desired here, as it creates consistency (a frame is always completely simulated, or not), does not introduce a new API or complicated addtional state in ezWorld.

If desired, I would take over the implementation of the solution for this issue.

**Comment by jankrassnigg** [comment]
TL,Dr, because I'm on vacation, but this is not how you are supposed to pause the game, it is for the editor use case and other special cases. Once the world simulation is enabled, disabling it again usually doesn't work as expected. 

Instead on the world call getclock, and on the world clock you can pause etc. 

Then the world simulation continues as usual, but the time step remains at zero. 

In rare cases components need to be fixed to not break with this. 

I have my own little game where I use this all the time, ie for a real-time-with-pause type of game.

**Comment by C-Core** [comment]
While I agree that you can simply pause the clock to pause a game it would still be nice if the WorldSimulationState would be consistent across a frame. Pausing a game that way would also have the benefit that update functions with the m_bOnlyUpdateWhenSimulating flag set would not be called and thus you could save some performance. 

To your proposed solutions:
1. I think I like this one the best, GetWorldSimulationEnabled should return the current state since you could query that during a frame in e.g. a component update. If it would return the desired state you would have the same inconsistency again.
2. You will most likely have code in your game state anyways that handles a pause menu or something like that. But that would be custom code so I would not take this solution, as you've already said, it creates a new API to achieve something you can already do.
3. While in theory this sounds like a nice solution you would need to pipe the current worldsimulationstate through all the functions. And it would still be inconsistent if the user calls GetWorldSimulationEnabled within a frame.

Feel free to open a PR.

**Comment by jankrassnigg** [comment]
Agreed that 1 should work properly. However for pausing usually the clock is the better choice.
