### ISSUE TITLE
[BUG] Main View (Camera) bug

### ISSUE THREAD

**Issue by kisstp2006** [ezEngine/ezEngine#1385]
**Bug description:**
When testing the game , the engine doesn't use the selected "Main Camera"

**How to Reproduce:**
1. Create a new project.
2. Then create an empty object
3. Add the camera component and set the "Usage Hint" to "Main View"
4. And run the game
**Screenshots:**
![image](https://github.com/user-attachments/assets/ea416dfe-5507-46aa-a152-6409630a9f0f)
I used the latest release version (24.09.0)

**Comment by jankrassnigg** [comment]
I would guess that you have more than one camera with the "Main View" usage hint. In that case the engine picks one of them. You can even switch through them with PageUp / PageDown.

Can you double check, that that's not the case ?

**Comment by kisstp2006** [comment]
I have one camera set to render to texture and another set to main view.
![image](https://github.com/user-attachments/assets/dd7135a1-698d-4098-8d42-89adb6fdf162)
![image](https://github.com/user-attachments/assets/1582a6eb-cf79-4cfe-a1ea-73848bb0cb56)
These are the cameras I have in the scene

**Comment by jankrassnigg** [comment]
You are correct, I was able to reproduce and fix it. See #1386.

**Comment by jankrassnigg** [comment]
A way to "fix" it for you:
* Press PageUp, it will then pick the main camera.
* OR: Use a [Player Start Point Component](https://ezengine.net/pages/docs/gameplay/player-start-point.html) to spawn a player prefab, which contains the main camera. This is the recommended approach for spawning your player anyway, and since most of our demos do this, we didn't noticed that it doesn't work properly without this.

**Comment by kisstp2006** [comment]
Thank you very much for your help, the second fix works !
