### ISSUE TITLE
Transform Gizmo not showing up in Orthographic views.

### ISSUE THREAD

**Issue by antonyjones67** [ezEngine/ezEngine#268]
**Bug description:**
Transform Gizmo not visible in Orthographic views. It only shows up in Perspective.

**How to Reproduce:**
Just switch to quad view. Select object and 
![NoTransformGizmo](https://user-images.githubusercontent.com/3905646/84977813-8ba57880-b0e8-11ea-9f28-dba929f3488e.jpg)
switch to translation Gizmo.

**Dev-branch commit hash:**
Dev Branch
Hash: bef8ac8fc68207df39290c6877b5738558fe09b2

**Comment by jankrassnigg** [comment]
This is by design. In orthographic views these modes work differently, and you won't see a gizmo. Just left-click and drag in the ortho view to translate, rotate or scale along the main axis or plane.

The documentation mentions this:
http://ezengine.net/scenes/gizmos.html

However, it doesn't make it clear, that you won't see a gizmo. I will update the documentation to make it clearer.

One could argue that the ortho modes should indicate more clearly, what mode is active, however I simply don't know how (with reasonable effort).

**Comment by jankrassnigg** [comment]
Added a note to the docs to point this out.
