### ISSUE TITLE
[FEATURE]Add camera preview to prefab editor

### ISSUE THREAD

**Issue by jayrulez** [ezEngine/ezEngine#336]
When editing a prefab cameras do not have a preview like they do in the scene editor window.

It would be useful to have a preview of the selected camera when editing prefabs.

**Comment by jankrassnigg** [comment]
They do have a preview, like in the scene. Maybe you had it deactivated. You have to enable the 'visualizers':

![image](https://user-images.githubusercontent.com/6001174/95959329-97891900-0e02-11eb-8b06-2b6af08de9b3.png)

Also, the preview camera doesn't use the ambient lighting that is typically enabled in prefabs, but disabled in scenes (View > Add Ambient Light). Therefore, the preview is often entirely black, which makes it easy to miss. In the screenshot above I added a point light, and you can see that the preview only lights the scene with that, whereas the editor view also uses the ambient light. Actually, why that is the case, I would have to investigate (I assume it's because of exclusion tags set on the ambient light objects, to prevent them from being exported).

I guess the ambient light option could be enabled in the preview as well, though then the preview wouldn't show EXACTLY how the scene would look like later.

**Comment by jayrulez** [comment]
Yeah, it was the lack of lighting that tripped me up there.
