### ISSUE TITLE
Editor is unresponsive while cubemap texture is being transformed.

### ISSUE THREAD

**Issue by jayrulez** [ezEngine/ezEngine#342]
**Bug description:**
The editor becomes unresponsive when a cubemap texture is being transformed and remains so until the transformation is finished.

**How to Reproduce:**
Create a texture cubemap asset and assign the inputs.
Click the transform button.

The editor becomes unresponsive and is not usable until the asset is transformed.

**Comment by jankrassnigg** [comment]
This is actually the expected behavior. When you click the transform button, it is a blocking operation. For some assets this can take long.

You can enable the background asset processing, and then just 'save' a document, then it won't block, but if you press the transform button, it will always block.
