### ISSUE TITLE
Procedural mesh primitives use lowest detail as their default configuration

### ISSUE THREAD

**Issue by jayrulez** [ezEngine/ezEngine#347]
**Bug description:**
Apart from the box primitive, all the other primitives seem to me generated incorrectly in the editor.

**Screenshots:**
![image](https://user-images.githubusercontent.com/78807/100397779-94946180-3019-11eb-8b44-3b7275c054f2.png)

![image](https://user-images.githubusercontent.com/78807/100397795-af66d600-3019-11eb-93f0-ecc0c7dcd1f0.png)

![image](https://user-images.githubusercontent.com/78807/100397810-c7d6f080-3019-11eb-8d16-28589a8f9846.png)

![image](https://user-images.githubusercontent.com/78807/100397824-d91ffd00-3019-11eb-8ada-6f3dc1c5fb4b.png)

![image](https://user-images.githubusercontent.com/78807/100397845-f228ae00-3019-11eb-8f5d-ba85a1792d83.png)

![image](https://user-images.githubusercontent.com/78807/100397858-066cab00-301a-11eb-9330-15ddb6dd91a0.png)

I didn't bother screen-shotting all of them since these should be enough.

**Comment by jankrassnigg** [comment]
These are simply the default configuration for each mesh type, which is the lowest detail representation of each type. You would need to adjust the "detail" options. Since this is not very intuitive, I've changed the default behavior to produce nicer versions of each object type.
I've also updated the docs a little: http://ezengine.net/graphics/meshes/mesh-asset.html

**Comment by jayrulez** [comment]
Thanks!
