### ISSUE TITLE
[FEATURE]Modernize RenderFoundation API

### ISSUE THREAD

**Issue by jayrulez** [ezEngine/ezEngine#349]
As a follow up to the topic here: https://github.com/ezEngine/docs/wiki/Vulkan-Support

I do agree that the best way to Vulkan support for ez is to upgrade the RenderFoundation API in place to properly abstract it for both Vulkan and DX11 (at least).

I've experimented with porting two separate low level APIs to ezEngine from WickedEngine and Veldrid (A C++ port of the C# code using ez base libraries).

Both experiments worked to some extent and I've gained a little bit of experience with some low level graphics programming. I believe with that I may be able to help with modernizing the ez RenderFoundation.

Comparing ez to these other libs (with are considered modern) at a high level, these are the things I think we should be looking into for modifying RenderFoundation:

1. Command lists
This encapsulates a list of commands that can be submitted to the device in the order that they were recorded.
A command list would do essentially what Context does. However, instead of submitting each command immediately, the commands are recorded and submitted at once.

In DX11, this can be achieved by creating a deferred context per abstracted command list and create a native command list from the deferred context then submit then execute the command list using the immediate context.
Command lists would not be thread safe but you can create a command list for any thread, record commands there and execute them on the main/render thread using the immediate context.
I think implementing command lists like this in D3D11 is not necessary though but would bring it a lot closer to the potential vulkan port.

This could be implemented without too much changes to many changes to the consuming code. The Command list feature could exist alongside the current Context class until everything is upgraded to use it.

I could actually work on this as it is low hanging.

2. Monolithic pipeline state
In newer graphics APIs, the pipeline state is created upfront and set as a monolith. Pipeline states can be cached to avoid recreating them when it is not necessary.

In DX11, an abstracted pipeline state would encapsulate your shaders, blend, rasterizer states etc...
Again, implementing this for DX11 would be only to make it look more like Vulkan.

This is something I could also work on for the most part.

3. Render Passes
We could use this as a start https://developer.samsung.com/galaxy-gamedev/resources/articles/renderpasses.html

@C-Core @jakrams if you have any thoughts about the design you'd like please leave them here.

**Comment by C-Core** [comment]
Thanks for your summary. Here is a bit more detail on our current plan:

We discussed the RendererFoundation refactoring in the team a while ago and I started to work on it already. My refactorings would address Render Passes and Command Lists. The idea is the following:

We have two new functions on the device called Begin/EndPass. It will return a GALPass object. On Vulkan this would map to a render pass, on DX11 it would do nothing.

On the GALPass you have Begin/EndRendering and you have to pass the rendertarget setup and whether you want to clear etc to begin. Additionally you have Begin/EndCompute. These functions will return a specific GALCommandRecorder. GALRenderCommandRecorder for rendering and GALComputeCommandRecorder for compute. Each has only the necessary functions for rendering or compute and some shared functions for resource binding etc. These command recorders will replace GALContext. On Vulkan this would map to a subpass.

CommandLists are never handed to the user explicitly but are only used under the hood in the command recorder implementations. In DX11 we will not use commandlists at all but the command recorder will directly execute on the immediate context. Deferred contexts in DX11 are way to slow and pretty much useless. Furthermore we only want to spend the least effort as possible on DX11 since we won't support it anymore once Vulkan is in a good shape. We also want to change a few things in the renderer which would be really hard to support in DX11, like e.g. switching to bindless resources.

Regarding the monolithic pipeline state we decided to not expose that to the user, but build and cache the pipeline state under the hood. The information to create the pipeline state comes from many different sources like materials, shader, meshes, render pipelines etc. so it would be pretty difficult to create the state up front. Also some modern APIs allow to set the state on a finer granularity like e.g. consoles because the hardware actually doesn't need one monolithic pipeline state. 
So for now we will leave the state APIs as is until we have gathered more experience with performance etc.

This is our current plan. I would be very curious to hear your opinion on that, so let me know what you think.

**Comment by jayrulez** [comment]
This sounds great actually. 

It is a little different from what I was thinking but wrt. handing command lists to the user.
However, I do not see a issue with it at all.
