### ISSUE TITLE
Picking scale manipulator axis does not scale in the expected direction.

### ISSUE THREAD

**Issue by antonyjones67** [ezEngine/ezEngine#602]
When I pick the scale manipulator axis and drag it does not scale in the direction I would expect.

1. Load Testing Chambers - Corridor.
2. Find 2 gray spheres next to red barrel similar to gif provided.

![ScaleManipulatorBug](https://user-images.githubusercontent.com/3905646/177064344-2015fd7e-bea4-4959-bcfe-fa3155965347.gif)

Commit Hash:
fc2895e70a1c96c58aabe3b16c0b6944897a3830

Intel 7
48 Gig Ram
GPU 2070 RTX

**Comment by jankrassnigg** [comment]
This is indeed normal for the scale gizmo. It doesn't take the orientation of the gizmo into account, but rather moving the mouse right or up scales things up, and left or down scales things down.
That's because scale is different to translation and rotation, where the change is equally reflected on all selected objects (and attached child objects). Scale can't be propagated that way, as it would often introduce shearing. Something that game engines generally don't support. Therefore changes to scale are always in local-space and therefore the orientation of the gizmo is quite arbitrary. It only happens to align properly with the object under simple conditions.
