### ISSUE TITLE
[BUG] Creating new scene cameras doesn't work with shortcut (Ctrl+Alt+Number)

### ISSUE THREAD

**Issue by jankrassnigg** [ezEngine/ezEngine#763]

**Comment by Sanakan8472** [comment]
This is due to a bug in Qt: https://bugreports.qt.io/browse/QTBUG-60768. Pressing Ctrl+Alt+4 is recognized by **QKeyEvent** as well as by **QKeySequenceEdit** as Ctrl+Alt+€. You could just change the shortcut to that and it will work but it's obviously keyboard layout dependent and not the ideal solution.

**Comment by jankrassnigg** [comment]
So the only proper fix would be to use a different key combination.

The reason this one was chosen, is that CTRL+Number stores a user's favourite camera and "Number" selects that camera. Now we need something else for creating scene cameras, therefore ALT was added to the mix.

It doesn't seem to work with SHIFT at all, though, I guess because shift actually modifies the character.

Any other ideas? Not sure whether Qt distinguishes between numbers and the numblock ? Otherwise we could use "Ctrl+Numpad 1" etc.

Only ALT doesn't work either, because that gives focus to the main menu.

**Comment by jankrassnigg** [comment]
I don't see an alternative shortcut that could be used. About half of them work, and jumping to the cameras works for all shortcuts.

Closing this issue now. Maybe Qt fixes this at some point. In the meantime, for some combinations people just have to use the menu.
