### ISSUE TITLE
[FEATURE] Name of the parameters

### ISSUE THREAD

**Issue by Geniok** [ezEngine/ezEngine#836]
**Is your feature request related to a problem? Please describe:**

Introduce the ability to display the name of the parameters not as they are described in the code, but through synonyms.

It would be more logical to hide the internal implementation from the user, and show him a replacement symbol, which may be shorter or longer than what is currently displayed.

**Describe the solution you'd like:**
LocalPosition-> Position
LocalUniformScaling -> UniformScaling
UseAsOccluder -> Use as occluder

**Additional context:**

![2022-12-23_091622](https://user-images.githubusercontent.com/3386000/209282673-a789e1ee-655c-4b62-ad12-0e4f863fbd48.png)

![2022-12-23_091643](https://user-images.githubusercontent.com/3386000/209282703-05969d34-aaeb-48e0-a854-0aa15fc8cefb.png)

**Comment by jankrassnigg** [comment]
We do have a feature for translating UI strings, and we use that for component names, enums and so on, but we don't usually use it for component properties. We could, but the system has some shortcomings at the moment, which should get fixed at some point. For example we should use the full type string to look something up (e.g. "FooComponent::BarProperty") rather than just "BarProperty", to avoid name collisions.
