### ISSUE TITLE
When working with a Custom plugin, and launching the editor from code I always get the "Compile this project's C++ plugin?"

### ISSUE THREAD

**Issue by antonyjones67** [ezEngine/ezEngine#960]
I always get this dialog when launching the editor from visual studio, even though I know the "Custom" plugin has been compiled already.
![image](https://github.com/ezEngine/ezEngine/assets/3905646/9b1ab93a-c68c-4834-b9e0-e14d05899eae)

**Comment by jankrassnigg** [comment]
The editor checks whether the DLL exists on disk. If it doesn't find the DLL, then either you don't have exactly the one compiled that it wants (e.g. you compiled it in Debug, but the editor runs in Dev) or the editor somehow looks in the wrong directory.

1. What happens when you let it compile the DLL? Does it then still show the message the next time?
2. Could you check whether it searches in the wrong place? Just search the code for the error message, and put a breakpoint there. Then compare the path that the editor checks, and the one where your plugin really ends up.

It's also possible that something got misconfigured. The editor uses a "YourPluginName.ezPluginBundle" config file to read some information, such as the DLL output name. Maybe there's something wrong in there. But then I'd expect the runtime to also not load the correct DLL.

**Comment by antonyjones67** [comment]
1. I have not yet tried to let it compile, because it will crash when I launch the editor from VS. 2. Sure I can look into it. As far as the platform, I am compiling "Debug" for both the plugin and the editor. I created this plugin before your workflow changes. I may have some strange hybrid situation going on here. I will let you know what I find out. Thank you.

**Comment by jankrassnigg** [comment]
Compiling indeed doesn't work as long as VS is attached to the editor. Run the editor without a debugger (CTRL+F5 from VS), then it should work.
For some reason the MSVC compiler doesn't like compiling stuff while someone is debugging...
I think I've added warnings to all those code paths though, you should see a message box telling you about that.

**Comment by antonyjones67** [comment]
Hitting apply while not attached to VS seemed to fix the issue for me. Thank you.
