### ISSUE TITLE
Why it's downloading Qt6?

### ISSUE THREAD

**Issue by ghost** [ezEngine/ezEngine#993]
I'm running cmake configuration directly and cmake tells it's downloading Qt6?

`-- Downloading 'Qt6-6.4.0-vs143-x64..7z'...`

**Comment by Ingrater** [comment]
On windows we provide a precompiled minimal set of QT libraries which ezEngine uses for all it's UI tools (Editor, Inspector, etc).
If you do not manualy provide a install of Qt 6 through the `EZ_QT_DIR` cmake variable, cmake will automatically download the prebuild qt package. You can also disable all Qt support using the cmake variable `EZ_ENABLE_QT_SUPPORT` but this will also remove all UI Tools from the build. See https://ezengine.net/pages/docs/build/cmake-config.html for details.

So this is not a bug, it is fully intentional behavior.
